### ISSUE TITLE
How to mark page as patrolled

### ISSUE THREAD

**Issue by SolidBlock-cn** [Awesome-Aasim/WikiRCPatrol#1]
I'm using RCPatrol in my wiki (not Wikipedia), and can successfully view recent changes. But I can't find a button to efficiently mark page as patrolled. Besides, if that's a bunch of several edits, I don't know how to mark the several page as patrolled at one click. Therefore, the red "!" will still display in my RC.

**Comment by Awesome-Aasim** [comment]
I have not implemented a "patrol" button yet despite me planning to although I definitely should aha.

I am currently busy with other work related matters so it may be a while before it is implemented. If you can submit a pull request I can review your changes then merge them with the main wiki script. :)

**Comment by SolidBlock-cn** [comment]
PRed. Marking a bunch of edits as patrolled is yet not supported.

**Comment by SolidBlock-cn** [comment]
I added the future of patrolling multiple edits in my own wiki. It does not look at page history, but auto merge edits within rc table. You can see https://rs.miraheze.org/wiki/User:SolidBlock/rcpatrol.js.

**Comment by SolidBlock-cn** [comment]
I found you checked "result.error" to determine where the command errors. Would it be better to simply use .success or .error instead of .done?

**Comment by Awesome-Aasim** [comment]
Hi, I finally got time to review your edits. They look good, thank you so much for your contribution!
